name: 'composite_workflow_example'
description: 'Composite workflow example'
inputs:
  abi_version:
    description: 'Specify abi version to initialize, only when skip_abiinstall is false'
    required: false
  ingredient_path:
    description: 'Specify ingredient_path, only when skip_abiinstall is false'
    required: false

runs:
  using: "composite"
  steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Present Working Directory
      run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      shell: bash
    # //TODO: check if already installed then dont install again, unless force install specified.
    - name: "Run abi_init"
      id: "ABIInstall"
      run: |
        echo ${{ inputs.ingredient_path }}
        echo ${{ inputs.abi_version }}
        echo ${{ env.MANIFEST }}
      shell: bash
