name: 'composite_workflow_example'
description: 'Composite workflow example'
inputs:
  abi_version:
    description: 'Specify abi version to initialize, only when skip_abiinstall is false'
    required: false
  ingredient_path:
    description: 'Specify ingredient_path, only when skip_abiinstall is false'
    required: false

runs:
  using: "composite"
  steps:
    # //TODO: check if already installed then dont install again, unless force install specified.
    - name: "Run abi_init"
      id: "ABIInstall"
      run: |
        echo "Ingredient Path: ${{ inputs.ingredient_path }}"
        echo "ABI Version: ${{ inputs.abi_version }}"
        echo "Manifest File: ${{ env.MANIFEST }}"
        echo "TRIVY_SCAN_INTERMEDIATE_FOLDER=${{ format('{0}/{1}', 'Jellow', 'TrivyScan') }}" >> $GITHUB_ENV
        echo "${{ toJSON(env) }}" 
      shell: bash
    
    - id: set_variable
      run: echo "VariableValue=Hello, World!" >> $GITHUB_OUTPUT
      shell: bash
      
    - run: |
        my_variable=${{ steps.set_variable.outputs.VariableValue }}
        formatted_string="Formatted: {{ format('Value: {0}', steps.set_variable.outputs.VariableValue) }}"
        echo "$formatted_string"
      shell: bash
