name: BundleInstaller

on:
  workflow_dispatch:
    inputs:
      QCAgentRef:
        required: false
        default: "master"
        type: string
        description: 'Branch name for QC Agent repo to download artifacts'
      ReleaseBuild:
        description: 'Enable for Release Build trigger'
        required: false
        type: boolean
        default: false
      Scans:
        description: 'Enable to run all Scans'
        required: false
        type: boolean
        default: false
      UnitTesting:
        description: 'Enable for Unit Testing trigger'
        required: false
        type: boolean
        default: true
      SdleAutomation:
        description: 'Enable SDLe Automation'
        required: false
        type: boolean
        default: false
      SdleAutomationDryRun:
        description: 'Enable SDLe Automation in Dry Run Mode'
        required: false
        type: boolean
        default: false
      SdleUrl:
        description: 'Enter SDLe Submission URL'
        required: false
        type: string
        default: ''
      SdleId:
        description: 'Enter SDLe Project ID'
        required: false
        type: string
        default: ''
  push:
    branches-ignore:
      - "release_*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Job
        run: echo "Running BundleInstallerRelease"
