name: My Workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      parameter1:
        description: 'Input parameter 1'
        required: true
      parameter2:
        description: 'Input parameter 2'
        required: true

jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run my script
      run: |
        echo "Input Parameter 1: ${{ github.event.inputs.parameter1 }}"
        echo "Input Parameter 2: ${{ github.event.inputs.parameter2 }}"
