name: daily-report

on:
  schedule:
    # - cron: '*/5 * * * *'
    - cron: '* 14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: "Hello World"
        if: github.event.schedule == '* 15 * * *'
        run: |
           echo "Hello World, This Test Branch"
        shell: bash
