name: ExpandedBundleInstaller1
on:
  workflow_run:
    workflows: [BundleInstallerRelease]
    types:
      - completed
    branches:
      - release_*
      - main

jobs:
  expanded:
    runs-on: ubuntu-latest
    steps:
      - name: Expanded Job
        run: echo "Running ExpandedBundleInstaller after Release is done!"
      - name: Branch_Name
        run: echo "${{ github.event.workflow_run.head_branch }}"
      - name: Workflow_Branch_Main
        run: echo "main"
