name: "reusable workflow"

on:
  workflow_call:
   inputs:
      config-path:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello"
        run: |
          echo ${{ inputs.config-path }}
        shell: bash
      - name: "Hello"
        run: |
          echo ${{ inputs.config-path }}
        shell: bash
      - name: "Hello"
        run: |
          echo ${{ inputs.config-path }}
        shell: bash
      - name: "Print Environment"
        run: |
           echo ${{ vars.COVERITYCSHARPSTREAM }}
        shell: bash
