name: 'Shell Commands'
on:
    - push
jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            -
                name: 'echo a string'
                run: 'echo "Hello World"'
            -
                name: 'multiline script'
                run: "node -v\nnpm -v\n"
            -   name: 'python Command'
                run: |
                   import 
                   print(platform.processor())
                shell: python