name: Test Enivornment Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Present Working Directory
        run: |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
            echo "${{ github.token }}"
      # - name: "Set Enviroment Variable"
      #   run: |
      #       source my_env.env && export $(sed '/^#/d' my_env.env | cut -d= -f1)
      #   shell: bash
      - name: "Set Enviroment Variable"
        run: |
           export KlocworkProject="sample_windows"
           export KlocworkCSharpProject="sample_windows_csharp"
           export CoverityStream="CCG-ADO-BA-SAMPLE-WINDOWS-C-DEVELOP"
           export CoverityCSharpStream="CCG-ADO-BA-SAMPLE-WINDOWS-CSHARP-DEVELOP"
        shell: bash
      - name: "Print Build Config File."
        run: |
            cat BuildConfig.json
        shell: bash
      - name: "Print Build Config Copy File."
        run: |
            cat BuildConfig_copy.json
        shell: bash
